name:                 Haskell-Solution
version:              0.1.0.0
visibility:           public
id:                   Haskell-Solution-0.1.0.0-D26zpJmJuLTFRVZxWU7MH2
key:                  Haskell-Solution-0.1.0.0-D26zpJmJuLTFRVZxWU7MH2
license:              BSD-3-Clause
copyright:            2026 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/Haskell-Solution#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/Haskell-Solution#readme>

abi:                  87eed0b092d943afe82d8b164d4e637a
exposed:              True
exposed-modules:
    CodeGen Interference Intermediate Lib Liveness Main Parser Target

hidden-modules:       Paths_Haskell_Solution
import-dirs:
    C:\Users\Me\Git-Shit\COMP3649-project-1-\.stack-work\install\c7b9857b\lib\x86_64-windows-ghc-9.10.3-b42a\Haskell-Solution-0.1.0.0-D26zpJmJuLTFRVZxWU7MH2

library-dirs:
    C:\Users\Me\Git-Shit\COMP3649-project-1-\.stack-work\install\c7b9857b\lib\x86_64-windows-ghc-9.10.3-b42a\Haskell-Solution-0.1.0.0-D26zpJmJuLTFRVZxWU7MH2
    C:\Users\Me\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\Me\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    C:\Users\Me\Git-Shit\COMP3649-project-1-\.stack-work\install\c7b9857b\lib\x86_64-windows-ghc-9.10.3-b42a\Haskell-Solution-0.1.0.0-D26zpJmJuLTFRVZxWU7MH2
    C:\Users\Me\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\Me\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    C:\Users\Me\Git-Shit\COMP3649-project-1-\.stack-work\install\c7b9857b\lib\x86_64-windows-ghc-9.10.3-b42a
    C:\Users\Me\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\Me\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    C:\Users\Me\Git-Shit\COMP3649-project-1-\.stack-work\install\c7b9857b\share\x86_64-windows-ghc-9.10.3-b42a\Haskell-Solution-0.1.0.0

hs-libraries:         HSHaskell-Solution-0.1.0.0-D26zpJmJuLTFRVZxWU7MH2
include-dirs:
    C:\Users\Me\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include

depends:              base-4.20.2.0-39f9 containers-0.7-c2a5
haddock-interfaces:
    C:\Users\Me\Git-Shit\COMP3649-project-1-\.stack-work\install\c7b9857b\doc\Haskell-Solution-0.1.0.0\Haskell-Solution.haddock

haddock-html:
    C:\Users\Me\Git-Shit\COMP3649-project-1-\.stack-work\install\c7b9857b\doc\Haskell-Solution-0.1.0.0
